/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prog.sandbox.probepruefung.one;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

}
